## Brew taps

# Brew packages
brew 'ant'
brew 'autoconf'
brew 'bash-completion'
brew 'cmake'
brew 'dwdiff'
brew 'freetype'
brew 'gettext'
brew 'git'
brew 'git-flow'
brew 'git-tracker'
brew 'glib'
brew 'gnu-tar'
brew 'icu4c'
brew 'imagemagick'
brew 'jpeg'
brew 'libffi'
brew 'libpng'
brew 'libtool'
brew 'maven'
brew 'nvm'
brew 'openssl'
brew 'ossp-uuid'
brew 'pkg-config'
brew 'postgresql'
brew 'redis'
brew 'rename'
brew 'rmtrash'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'sqlite'
brew 'libyaml'

# Cask applications
cask 'cyberduck'
cask 'docker'
cask 'eclipse-java'
cask 'flip4mac'
cask 'flux'
cask 'google-chrome'
cask 'hipchat'
cask 'postico'
cask 'rdm'
cask 'sourcetree'
cask 'sublime-text'
cask 'tidal'
cask 'virtualbox'
cask 'xquartz'

# App Store applications
